FROM solr:7.1.0
COPY ./config/solr/schema.xml /opt/solr/server/solr/configsets/_default/conf/schema.xml
COPY ./config/solr/solrconfig.xml /opt/solr/server/solr/configsets/_default/conf/
USER root
RUN chown -R solr:solr /opt/solr/server/solr/configsets/_default/conf
USER solr

CMD ["/opt/solr/bin/solr", "-f"]